Added WebService uptime metric in iis collector
prometheus-community/windows_exporter pull request #1059
Opened 2022-09-06 12:45 UTC by kaffarell

Added the WebService uptime metric in the iis collector. This metric is
a counter and counts up the seconds when the service is up. If the
service is stopped, the uptime is 0.

2022-09-09 09:58 UTC, breed808 requested changes
Thanks for adding this. I've left one minor comment to be addressed, then this will be good to merge.

2022-09-09 09:58 UTC, breed808 commented on docs/collector.iis.md
> +`windows_iis_service_uptime` | _Not yet documented_ | counter | `site`
This should be set to a `gauge` type.

2022-09-10 00:11 UTC, breed808 approved these changes
Looks good! Could you rebase your branch off `master` to remove the merge commit (052964a872d1635ddac0f9e3a7797414ef77f7b2) from the PR?

2022-09-12 20:33 UTC, breed808 commented
@kaffarell You'll need to amend the most recent commit by signing it `git commit --amend --no-edit -s` in order to pass the failed CI check.

2022-09-13 14:43 UTC, kaffarell commented
Done @breed808 (sorry for the mess with git, had a rebase accident 😢)

2022-09-13 21:19 UTC, breed808 commented
It's all good. Thanks for your patience with this one :+1:

2022-09-13 21:19 UTC, merged