NPS(feature): add nps collector
prometheus-community/windows_exporter pull request #1188
Opened 2023-04-17 14:21 UTC by rebortg

The PR add the a NPS collector of server data from this 2 classes:

- Win32_PerfRawData_IAS_NPSAuthenticationServer 
- Win32_PerfRawData_IAS_NPSAccountingServer

2023-04-17 21:32 UTC, breed808 requested changes
Thanks for submitting this! Let me know if any clarification is needed on the comments.

2023-04-17 21:32 UTC, breed808 commented on collector/nps.go
> +}
The `init` function here will need to be removed, with the collector being registered in the [init.go](https://github.com/prometheus-community/windows_exporter/blob/b033ff71ffbd85e9774a9bdcc25c9cd91d1e5e8e/collector/init.go#L33) file.

2023-04-17 21:32 UTC, breed808 commented on collector/nps.go
> +func newnpsCollector() (Collector, error) {
Function should be renamed to `newNPSCollector` to fix the failing CI job.

2023-04-17 21:32 UTC, breed808 commented on collector/nps.go
> +// - <add link to documentation here>
Is there a documentation link for the two classes?

2023-04-29 20:19 UTC, breed808 requested changes
Removal of the `init()` function is good, but you need to add an entry in the `collectors` slice in [collectors/init.go](https://github.com/prometheus-community/windows_exporter/blob/master/collector/init.go#L28)

2023-05-02 07:41 UTC, rebortg commented
Done. I hope now all is correct

2023-07-10 20:02 UTC, breed808 approved these changes

2023-07-10 20:28 UTC, merged