Add Hyper-V CPUWaitTimePerDispatch metrics
prometheus-community/windows_exporter pull request #1220
Opened 2023-06-06 12:37 UTC by yuriyostapenko

Adds the following metrics for Hyper-V:
- `windows_hyperv_host_cpu_wait_time_per_dispatch`
- `windows_hyperv_vm_cpu_wait_time_per_dispatch`

This is one of key metrics for thoubleshooting overprovisioning, and was requested in https://github.com/prometheus-community/windows_exporter/issues/517#issuecomment-694710039.

2023-08-05 22:21 UTC, breed808 requested changes
Apologies for the delay in reviewing this! Both metric names will need a suffix (see comments) but everything else looks good :+1:

2023-08-05 22:21 UTC, breed808 commented on collector/hyperv.go
> +			prometheus.BuildFQName(Namespace, buildSubsystemName("vm_cpu"), "wait_time_per_dispatch"),
This will need a `_total` suffix in the metric name, as it is a `Counter`

2023-08-05 22:21 UTC, breed808 commented on collector/hyperv.go
> +			prometheus.BuildFQName(Namespace, buildSubsystemName("host_cpu"), "wait_time_per_dispatch"),
This will need a `_total` suffix in the metric name, as it is a `Counter`

2023-08-08 08:00 UTC, yuriyostapenko commented
@breed808, I've made the requested changes.

2023-08-08 20:30 UTC, breed808 approved these changes
Looks good :+1:

2023-08-08 20:30 UTC, merged