adds whitelist for exchange collectors
prometheus-community/windows_exporter pull request #642
Opened 2020-10-29 10:35 UTC by fischerman

related to #614 and #569 

The flag enables the windows_exporter to work with different exchange installations where not all performance counters are available. Detecting the installed roles would be even nicer, but is much more work. Either way this is a nice way of customizing the exporter.

As a side effect of this PR, the order in which the collectors are called is now fixed. As a result, if one of the sub collectors fails the returned metrics are now consistent.

2020-10-31 08:05 UTC, breed808 requested changes
Hi Björn, thanks for submitting this PR! I've added a couple review comments, have a look at them and let me know if there's any issues.
Whitelisting of the Exchange collectors might assist with performance in some scenarios, so this is welcome.

2020-10-31 19:20 UTC, fischerman commented
@breed808 I've implemented your feedback.

2020-11-01 02:12 UTC, breed808 approved these changes
Looks good! @carlpett do you want to have a look at this before it's merged?

2020-11-01 10:51 UTC, carlpett reviewed
Thanks! Looks good functionally, just some structural comments

2020-11-01 10:51 UTC, carlpett commented on collector/exchange.go
> +}
Bit of a nit, but we've tried to keep generic utility functions in collector.go, since they are shared across the entire package.

2020-11-01 10:51 UTC, carlpett commented on collector/exchange.go
> +	collectorWhitelist = make([]string, 0, len(exchangeAllCollectorNames))
Could we make this a field on the `exchangeCollector` type? If not, it at least needs a more exchange-specific name, since it is a package level var.

2020-11-01 11:52 UTC, fischerman commented
@carlpett Done! I've moved the whitelist in the struct. I don't have permissions to merge.

2020-11-01 12:36 UTC, carlpett commented
Great! One minor thing that struck me now that I took a final pass was if whitelist is the right term here, since there is no corresponding blacklist? I think we usually just have `enabled` in similar places (eg `collectors.enabled` and `collector.mssql.enabled`)
Sorry for not thinking about it in the previous check!

2020-11-01 17:05 UTC, fischerman commented
Agreed! I've renamed it. Ready to merge from my side. Looking forward to v0.15 :)

2020-11-01 17:25 UTC, carlpett approved these changes
:tada: Thanks!

2020-11-01 17:26 UTC, merged

2020-11-20 10:29 UTC, rmyhren commented
Wow, this is great. Thanks for the work, @fischerman. We have not had the time to dig into this yet. Another benefit of providing upstream commits 👍