fix PercentTimeinGC metric
prometheus-community/windows_exporter pull request #999
Opened 2022-06-03 12:54 UTC by trunov-ms

Fix bug for counting value PercentTimeinGC
From program WEBMTest.exe in class Win32_PerfRawData_NETFramework_NETCLRMemory found counter type
`[DisplayName("% Time in GC"): ToInstance, *countertype(537003008)*: ToInstance, perfindex(2606): ToInstance, helpindex(2607): ToInstance, defaultscale(0): ToInstance, perfdetail(100): ToInstance] uint32 PercentTimeinGC`
The mapping for coutertype 537003008 is *PERF_RAW_FRACTION*.
For Cooking Type MSDN has formula (100 * CounterValue) / BaseValue
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/ms974615(v=msdn.10)?redirectedfrom=MSDN#perf_raw_fraction

2022-08-21 23:02 UTC, breed808 requested changes
Hi there, thanks for submitting this and a big apology for not reviewing sooner! I must have accidentally hit "read" on the notification for this pull request and subsequently missed it.

I've left a couple minor comments, let me know if any info is needed.

2022-09-01 13:19 UTC, trunov-ms commented on collector/netframework_clrmemory.go
> +	PercentTimeinGC_base               uint32
According this [article](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/ms974615(v=msdn.10)?redirectedfrom=MSDN#perf_raw_fraction) we should use this calculation
` (100 * CounterValue) / BaseValue`

And "_base" value is described as 
>... BaseValue—well, BaseValue is just a number used to make the calculation come out right. To be honest, we don't know exactly how the BaseValue is derived. Fortunately, we don't need to know how it's derived as long as we can figure out what the value is—something we'll show you how to do in a second.

Do you want the comment in the code?

2022-09-01 13:20 UTC, trunov-ms commented on collector/netframework_clrmemory.go
>  	PercentTimeinGC                    uint32
PercentTimeinGC is used in final calculation 
`float64(100*process.PercentTimeinGC)/float64(process.PercentTimeinGC_base)`

2022-09-03 00:17 UTC, breed808 commented on collector/netframework_clrmemory.go
>  	PercentTimeinGC                    uint32
Ah my mistake, I must have missed that when reviewing :facepalm:

2022-09-03 00:19 UTC, breed808 commented on collector/netframework_clrmemory.go
> +	PercentTimeinGC_base               uint32
I think a comment stating the base value is essentially a magic number would work. Linking to that article URL in the comment would also be good.

2022-09-09 09:44 UTC, breed808 approved these changes
Thanks for making those amendments. The file needs to be formatted with `gofmt` in order to pass CI.
Once that's done we can merge the changes.

2022-09-10 00:55 UTC, merged